name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build deps
        run: |
          sudo apt-get -q update
          sudo apt-get -y install autoconf automake build-essential git libtool libgmp-dev libsqlite3-dev python3 python3-mako net-tools zlib1g-dev libsodium-dev gettext
          sudo apt-get install -y valgrind python3-pip libpq-dev
          sudo apt-get install -y python3-setuptools libcurl4-openssl-dev libssl-dev clang-format
          pip3 install virtualenv
        shell: bash
      - name: Run linter
        run: clang-format -i *.c && git diff --exit-code
        shell: bash
      - name: Run build
        run: |
          git clone https://github.com/ElementsProject/lightning.git
          cd lightning
          git checkout v0.9.3
          python3 -m virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          cp ../esplora.* plugins/
          patch -p1 < ../Makefile.patch
          sed -i 's/PLUGINS=/PLUGINS=plugins\/esplora /g' Makefile
          sed -i 's/LDLIBS = /LDLIBS = -lcurl -lssl -lcrypto /g' Makefile
          ./configure
          make
          deactivate
        shell: bash
      - name: Upload Archive
        uses: actions/upload-artifact@v2
        with:
          name: esplora
          path: ./lightning/plugins/esplora